[tool.vulture]
ignore_names = ["test_*", "pytest*"]
paths = ["tests", "scripts", "yomikun"]

[tool.pytest.ini_options]
# Allow generated tests use readable Unicode names
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
# Search for module-inline tests
python_files = "*.py"
addopts = "--ignore=setup.py --ignore=scripts"

[tool.pyright]
venv = true
venvPath = ".env"

[tool.black]
skip-string-normalization = "true"

[tool.pylint.messages_control]
disable = [
    "missing-docstring",
    "logging-fstring-interpolation",
    "no-else-return",
    "line-too-long",
    "invalid-name",
    "too-few-public-methods",
    "no-value-for-parameter",
    "no-member",
    "broad-except",
    "inconsistent-return-statements",
    # I use pass to make lack of return obvious
    "unnecessary-pass",
    "no-else-raise",
    # I use """...""" for comments
    "pointless-string-statement",
    # Overriding 'input' is useful most of the time
    "redefined-builtin",
    "global-statement",
    # Noisy, but will revisit later
    "fixme",
    # Will revisit later
    "too-many-return-statements",
    "too-many-branches",
    "too-many-statements",
    "too-many-locals",
    "too-many-arguments",
    "too-many-public-methods",
    "too-many-instance-attributes",
]

[tool.pylint.design]
max-returns = 8
